name: Node.js CI

on:
    push:
        branches: [develop]

jobs:
    lint:
        runs-on: ubuntu-latest

        steps:
            - uses: actions/checkout@v2
            - name: Using Node.js ${{ matrix.node-version }}
              uses: actions/setup-node@v2
              with:
                  node-version: ${{ matrix.node-version }}
                  cache: "npm"
            - name: Installing dependencies
              run: npm install
            - name: Running eslint
              run: npm run eslint
            - name: Running CSS lint
              run: npm run stylelint
            - name: Running Prettier
              run: npm run prettier
